name: kbot ci/cd

on:
  push:
    branches: [ develop ]
    tags:
      - 'v*.*.*'

env:
  REGISTRY: ghcr.io

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run test
        run: make test

      - name: Build&Push
        env:
          APP: "kbot"
        run: make image REGISTRY=ghcr.io/bergshrund; make push REGISTRY=ghcr.io/bergshrund

  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: echo "VERSION=$(git describe --tags --abbrev=0 2>/dev/null)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      
      - uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag=strenv(VERSION)' helm/values.yaml
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "update version $VERSION"
          git push
          
      
    
